/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package za.co.bc.inventory.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import za.co.bc.inventory.model.Material;
import za.co.bc.inventory.service.MaterialService;

//import static sun.net.www.MimeTable.loadTable;

/**
 *
 * @author adolf
 */
public class MaterialForm extends javax.swing.JFrame {

    private MaterialService materialService;

    private DefaultTableModel tableModel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaterialForm.class.getName());

    /**
     * Creates new form MaterialForm
     */
    public MaterialForm() {

        initComponents();

        materialService = new MaterialService();

        tableModel = (DefaultTableModel) tblMaterials.getModel();

        loadTable();
        
        tblMaterials.setSelectionMode(
        javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblMaterials.getTableHeader().setReorderingAllowed(false);

        tblMaterials.setRowHeight(25);
        
        tblMaterials.setAutoResizeMode(
        javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void loadTable() {

        tableModel.setRowCount(0);

        List<Material> materials =
                materialService.getAllMaterials();

        for (Material material : materials) {

            tableModel.addRow(new Object[]{

                    material.getId(),
                    material.getName(),
                    material.getDescription(),
                    material.getCategory(),
                    material.getQuantity(),
                    material.getUnit(),
                    material.getSuppliers(),
                    material.getStatus()

            });

        }

    }
    
  

    private void clearFields() {

        txtName.setText("");
        txtDescription.setText("");
        txtQuantity.setText("");
        txtUnit.setText("");
        txtSupplier.setText("");
        txtSearch.setText("");

        cmbCategory.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtSupplier = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterials = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Description");

        jLabel3.setText("Category");

        jLabel4.setText("Quantity");

        jLabel5.setText("Unit");

        jLabel6.setText("Supplier");

        jLabel7.setText("Status");

        jLabel8.setText("Material Name");

        txtName.setText("Name");

        txtDescription.setText("Description");

        txtUnit.setText("Unit");

        txtSupplier.setText("Supplier");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleaning Chemicals", "Paper Products", "Cleaning Equipment", "Protective Equipment", "Kitchen Supplies", "Waste Management", "Consumables" }));
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Low Stock", "Out Of Stock" }));

        txtQuantity.setText("Quantity");
        txtQuantity.addActionListener(this::txtQuantityActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Description", "Category", "Quantity", "Unit", "Supplier", "Status"
            }
        ));
        tblMaterials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMaterials);

        txtSearch.setText("Search");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Materials Management ");

        jButton1.setText("Show all ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSupplier)
                            .addComponent(txtUnit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSearch)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    tableModel.setRowCount(0);

    List<Material> materials =
            materialService.searchMaterials(
                    txtSearch.getText()
            );

    for(Material material : materials){

        tableModel.addRow(new Object[]{

                material.getId(),
                material.getName(),
                material.getDescription(),
                material.getCategory(),
                material.getQuantity(),
                material.getUnit(),
                material.getSuppliers(),
                material.getStatus()

        });

    } // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblMaterialsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialsMouseClicked
         int row = tblMaterials.getSelectedRow();

    if(row==-1)
        return;

    txtName.setText(
            tableModel.getValueAt(row,1).toString()
    );

    txtDescription.setText(
            tableModel.getValueAt(row,2).toString()
    );

    cmbCategory.setSelectedItem(
            tableModel.getValueAt(row,3).toString()
    );

    txtQuantity.setText(
            tableModel.getValueAt(row,4).toString()
    );

    txtUnit.setText(
            tableModel.getValueAt(row,5).toString()
    );

    txtSupplier.setText(
            tableModel.getValueAt(row,6).toString()
    );

    cmbStatus.setSelectedItem(
            tableModel.getValueAt(row,7).toString()
    );

    }//GEN-LAST:event_tblMaterialsMouseClicked
    
    
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();

        tblMaterials.clearSelection();

        loadTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblMaterials.getSelectedRow();

        if(row==-1){

            JOptionPane.showMessageDialog(this,
                "Select a material first.");

            return;

        }

        int confirm = JOptionPane.showConfirmDialog(

            this,

            "Delete this material?",

            "Confirm",

            JOptionPane.YES_NO_OPTION

        );

        if(confirm != JOptionPane.YES_OPTION)
        return;

        int id = Integer.parseInt(

            tableModel.getValueAt(row,0).toString()

        );

        if(materialService.deleteMaterial(id)){

            JOptionPane.showMessageDialog(this,
                "Material Deleted!");

            loadTable();

            clearFields();

        }else{

            JOptionPane.showMessageDialog(this,
                "Delete failed.");

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblMaterials.getSelectedRow();

        if(row==-1){

            JOptionPane.showMessageDialog(this,
                "Please select a material.");

            return;

        }

        try{

            Material material = new Material();

            material.setId(
                Integer.parseInt(
                    tableModel.getValueAt(row,0).toString()
                )
            );

            material.setName(txtName.getText());
            material.setDescription(txtDescription.getText());
            material.setCategory(cmbCategory.getSelectedItem().toString());
            material.setQuantity(Integer.parseInt(txtQuantity.getText()));
            material.setUnit(txtUnit.getText());
            material.setSuppliers(txtSupplier.getText());
            material.setStatus(cmbStatus.getSelectedItem().toString());

            if(materialService.updateMaterial(material)){

                JOptionPane.showMessageDialog(this,
                    "Material Updated Successfully!");

                loadTable();

                clearFields();

            }else{

                JOptionPane.showMessageDialog(this,
                    "Update failed.");

            }

        }catch(Exception ex){

            JOptionPane.showMessageDialog(this,
                ex.getMessage());

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      // Validate Name
      if (txtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter the material name.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            txtName.requestFocus();
            return;
        }

        // Validate Description
        if (txtDescription.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a description.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            txtDescription.requestFocus();
            return;
        }

        // Validate Quantity
        if (txtQuantity.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter the quantity.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;
        }

        // Validate Unit
        if (txtUnit.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(this,
                "Please enter the unit.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            txtUnit.requestFocus();
            return;
        }

        // Validate Supplier
        if (txtSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter the supplier.",
                "Missing Information",
                JOptionPane.ERROR_MESSAGE);
            txtSupplier.requestFocus();
            return;
        }
  
        try {

            Material material = new Material();

            material.setName(txtName.getText().trim());
            material.setDescription(txtDescription.getText().trim());
            material.setCategory(cmbCategory.getSelectedItem().toString());
            material.setQuantity(Integer.parseInt(txtQuantity.getText().trim()));
            material.setUnit(txtUnit.getText().trim());
            material.setSuppliers(txtSupplier.getText().trim());
            material.setStatus(cmbStatus.getSelectedItem().toString());

            if (materialService.addMaterial(material)) {

                JOptionPane.showMessageDialog(this,
                    "Material added successfully!");

                  loadTable();
                  clearFields();
  
            } else {

                JOptionPane.showMessageDialog(this,
                    "Could not add material.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
 
            JOptionPane.showMessageDialog(this,
                "Quantity must be a valid number.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE);

            txtQuantity.requestFocus();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       loadTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MaterialForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMaterials;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupplier;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
